version: "3.9"

name: "athens"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PACKAGE_NAME: athens
        PACKAGE_VERSION: 0.11.0
        PACKAGE_VERSION_PREFIX: "v"
        PACKAGE_URL: https://github.com/gomods/athens
        PACKAGE_SOURCE_URL: https://github.com/gomods/athens/archive/master.tar.gz
        PACKAGE_HEAD_URL: https://github.com/gomods/athens.git
        PACKAGE_HEAD: true
        CACHEBUST: https://api.github.com/repos/issenn/docker-images-athens/git/refs/heads/master
        GO111MODULE: on
        GOPROXY: https://proxy.golang.org,direct
        CGO_ENABLED: 0
        BUILD_FLAGS: "-v"
